name: Build Windows EXE (Client)

on:
  workflow_dispatch:
  push:
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller==6.10.0

      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole --name "Bitseclab Copilot" app.py
          dir dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bitseclab-copilot-exe
          path: client/dist/Bitseclab Copilot.exe
